---
- name: 패키지 설치
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
  - name: 변수 포함(Include the variable file)
    ansible.builtin.include_vars: vars/main.yml

  - name: 작업 포함(inclue the tasks)
    ansible.builtin.include_tasks: tasks/main.yml

  - name: 최신버전 firewall 패키지 설치
    yum:
      name: "{{firewall}}" 
      state: latest

  - name: 방화벽 서비스 기동
    ansible.builtin.service:
      name: "{{ firewall }}"
      state: started
      enabled: true

  - name: 방화벽에 웹서비스 개시
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: enabled
      
  - name: "{{ web_root }}/index.html"  
    ansible.builtin.copy:
      content: "{{ ansible_fqdn }}(ansible_default_ipv4.address) has been customized by Ansible. \n"
      dest: "{{ web_root }}/index.html"