---
- name: 패키지 삭제
  hosts: lamp
  vars:
    firewall: firewalld
  tasks:
  - name: 변수 포함 (Include the varible file)
    ansible.builtin.include_vars: vars/main.yml

  - name: "{{ web_root }}/index.html 파일 삭제"  
    file:
      path: "{{web_root}}/index.html"
      state: absent
      
  - name: 방화벽에 웹서비스 내루기
    ansible.posix.firewalld:
      service: http
      permanent: true
      immediate: true
      state: disabled
    ignore_errors: true

  - name: 방화벽 서비스 내루기
    ansible.builtin.service:
      name: "{{ firewall }}"
      state: stopped
      enabled: true

  - name: stopped the database, web service
    service:
      name: "{{ item }}"
      state: stopped
      enabled: false
    with_items:
      - "{{ ansible_local.custom.services.db_service }}"
      - "{{ ansible_local.custom.services.web_service }}"
    ignore_errors: true

  - name: remove and start the database and web servers
    yum:
      name: 
        - "{{ ansible_local.custom.packages.db_package }}"
        - "{{ ansible_local.custom.packages.web_package }}"
      state: absent      
