---
- name: 잡 제어 플에이북 예제
  hosts: all
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    - name: 방화벽에 포트/서비스 제거
      firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: disabled
      with_items: "{{ fw_svc }}"
      ignore_errors: true

    - name: 웹 서버 삭제
      # files/index.html -> /var/www/html/index.html
      # files/localhost.key -> /etc/pki/tls/private/localhost.key
      # files/localhost.crt //etc/pki/tls/certs/localhost.crt
      file:
        path: "{{ item.dest }}"
        state: absent
      with_items: "{{ conf_files }}"

    - name: 웹 서비스 중지
      service:
        name: "{{ item }}"
        state: stopped
        enabled: false
      with_items:
      - httpd

    - name: 웹 최신 패키지 삭제
      yum:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
        - httpd
        - mod_ssl
