---
# Web Server Configuration
# ^ 1)Install packages
#     # yum install -y httpd mod_ssl
# ^ 2)Web Server Settings
#     # scp files/index.html ansible#:/var/www/html/index.html
# ^ 3) Web Server startup
#     # systemctl enable --now httpd
# ^ 4) Firewall registration
#     # firewall-cmd --permanent --add-service={http,https}
# ^ 5) SELinux(?)

- name: Install and start Apache HTTPD
  hosts: webservers
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name:
          - httpd
          - mod_ssl
        state: present

    - name: Web server settings
      copy:
        src: files/index.html
        dest: /var/www/html/index.html

    - name: Web service startup
      service:
        name: httpd
        state: started
        enabled: yes

    - name: Firewall registration
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled

    - name: Firewall registration - https
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled