---
- name: Remove and Stop Web Service
  hosts: all
  tasks:
# 1) 방화벽 서비스 OFF - http, https
    - name: (1) 방화벽 서비스 OFF - http, https
      firewalld:
        service: "{{ item }}"
        permanent: yes
        immediate: yes
        state: disabled
      loop:
        - http 
        - https
# 2) 서비스 OFF - httpd
    - name: (2) 서비스 OFF - httpd
      service: 
        name: httpd
        state: stopped
        enabled: no
      ignore_errors: yes
# 3) 서비스 설정 삭제 - /var/www/html/index.html
    - name: (3) 서비스 설정 삭제 - /var/www/html/index.html
      file:
        path: /var/www/html/index.html
        state: absent 
# 4) 패키지 삭제
    - name: (4) 패키지 삭제
      yum:
        name: 
          - httpd
          - mod_ssl
        state: absent