---
- name: DB 패키지 삭제
  hosts: database_prod
  tasks:
  - name: 서비스 종료
    ansible.builtin.service:
      name: mariadb
      state: stopped
      enabled: false

  - name: 패키지 삭제
    yum:
      name: "{{ pkg_db }}"
      state: absent
    vars:
      pkg_db:
      - mariadb-server
      - python3-PyMySQL
    when: ansible_distribution == 'CentOS'
    #when: ansible_distribution == 'RedHat'
  